### ISSUE TITLE
stacktrace-js mangles its output when used from other library

### ISSUE THREAD

**Issue by haf** [stacktracejs/stacktrace.js#164] opened 2016-05-20 15:36 UTC
I'm getting some really strange output from stacktrace-js when I run it in a browser:

<img width="426" alt="screen shot 2016-05-20 at 17 27 02" src="https://cloud.githubusercontent.com/assets/193115/15432979/a22f6594-1eb0-11e6-8846-ecf2be295b46.png">

I created a detailed question about this here: https://stackoverflow.com/questions/37350388/webpack-umd-seemingly-breaks-stacktrace-js-functionality
## Expected Behavior

Stacktrace-js should return the stacktrace and not return this strange output.
## Current Behavior

Instead I get the screenshot above as output.
## Steps to Reproduce (for bugs)

See the stackoverflow question. In short;

``` bash
npm install --save logary
```

[Initialise logary](https://github.com/logary/logary-js#examples):

``` js
import {
  default as Logary,
  Targets,
  ajax,
  createContent,
  Middleware,
} from 'logary';

export default () => {
  // once per site/app
  const target = Targets.logaryService({
    path: '/i/logary',
    serialise: createContent,
    send: ajax
  });

  return new Logary('example.com', target, [
    Middleware.messageId,
    Middleware.stacktrace,
    Middleware.timestamp
  ]);
};
```

Use logary that uses stacktrace-js in turn:

``` jsx
import React, { PropTypes } from 'react';
import { build, getLogger, LogLevel, Message } from 'logary';

const ErrorLogging = React.createClass({
  contextTypes: {
    logary: PropTypes.object.isRequired
  },

  getInitialState() {
    const { logary } = this.context;
    return {
      logger: build(logary, getLogger(logary, 'ErrorLogging'))
    };
  },

  errorOut() {
    const { logger } = this.state;

    try {
      throw new Error("this is bad, but it's just a test!");
    } catch (e) {
      logger(Message.eventError('Erroring out for fun', e, {
        isDeveloper: 'probably'
      }));
    }
  },

  render() {
    return <p>
      Unbound handler: <button onClick={this.errorOut}>Error out</button>
    </p>;
  }
});

export default ErrorLogging;
```
## Context

I'm trying to make it so that `Message.errorEvent` automatically parses the errors' stacktraces in logary-js, which is an open source software.
## Your Environment

This seems to happen in all browsers we try. I'm on OSX w/ evergreen Firefox, however. Doesn't happen in mocha during testing.
## Possible Solution

No idea. I'm having trouble debugging it, can't reproduce it during unit testing (albeit that's not a browser). I might add your karma/browserstack tests to logary-js to reproduce it? Or perhaps it's related to how webpack uses umd packing?

**Comment by eriwen** [comment] 2016-05-23 02:36
I've reproduced the behavior described with the tests of logary-js, but haven't had the chance to reproduce with browsers yet. 

I notice that you're using `inline-source-map` for webpack in testing but `source-map` otherwise. Perhaps that would explain the difference in behavior? 

Aside, I think that [error-stack-parser](github.com/stacktracejs/error-stack-parser) may be sufficient for your needs if all you want is parsing `Error`s. Does using that improve behavior? If so, that may point to a problem with source map resolution.

**Comment by mavnn** [comment] 2016-05-23 12:51
Hi @eriwen!
I'm working with @haf on this project, and I attempted to use error-stack-parser, which unfortunately exhibits the same behaviour.

Using source-map instead of inline-source-map also has no impact on behaviour (parsing succeeds in karma, but does not in the browser). If you have any other ideas we could try we'd love to hear about it!

Thanks for your time!

**Comment by mavnn** [comment] 2016-05-23 12:56
You can find the updated logary-js at https://github.com/mavnn/logary-js/tree/feature/error-stack-parser if that helps in investigations.

**Comment by haf** [comment] 2016-06-05 17:26
@eriwen Any news on this?

**Comment by haf** [comment] 2016-07-05 11:30
@eriwen Any news on this?

**Comment by haf** [comment] 2016-08-16 17:13
Ping, any news?

**Comment by oliversalzburg** [comment] 2016-08-16 18:04
Is there any way to get a minimal reproducible example of this problem? All code posted so far is a nightmare and I am not surprised that the outcome is not as expected.

I cloned https://github.com/logary/logary-js/tree/uglify-js-options and the npm scripts don't work cross-platform, the karma config is written in CoffeeScript (and coffee-script is not included as a dependency), the whole thing is bundled with webpack, requires transpiling with babel, ...

I would assume once you start shaving off a couple of layers, the problem becomes much clearer and possibly easier for others to work on as well.

**Comment by haf** [comment] 2016-08-16 20:31
Sorry you're having bad dreams about my code. I obviously don't think it's a nightmare, but each to his own. I can work with the constructive feedback you give.

 1. The npm scripts work cross platform AFAIK; can't see any reason for them not to? No absolute paths, only installed packages are called.
 2. Karma – do you need to use karma? Would it help if I rewrite it in JS?
 3. The whole point of this issue is that I want a common toolchain to build sites and libraries. Webpack gives me that. Should I assume you don't like the latest JavaScript version, from your comments? What do you suggest we use instead?
 4. What layers? Babel compilation?

**Comment by oliversalzburg** [comment] 2016-08-17 09:59
1. Your npm scripts assume they're being run on a POSIX compliant shell, which is not the case on Windows OS. Here, npm will run them through the Windows Command Prompt, which does not understand having commands prefixed with environment variables. If one expects their npm scripts to be processed by a specific shell, the npm script should invoke that shell.

2. Given that, from what I understand, the bug is specific to browser environments, Karma would seem like a good starting point to approach the problem systematically. Given that a configuration for Karma already exists in the project, I thought this is at least partially set up already.

3. I have no problems with the latest JavaScript version, but I have a problem with the requirement to transpile source code to be able to use it. That just introduces another possible source of errors into the process. Use whatever runs natively on the platform you're targetting. At least when investigating the source of an issue. If the issue is only visible if transpiling is taking place, then it's unlikely to be an issue with the original source.

4. I still don't really see what the actual issue here is and at what point it is introduced. There's transpiling, mangling, bundling, code optimizations from webpack, ...

It's not like one can just drop the snippets above into a file and run them in the browser to see the problem. That is just annoying. If I need 30 minutes to set up the scaffolding to reproduce an issue, it doesn't make me want to look into it. If I clone an example project and it doesn't work out of the box and still doesn't run after 10 minutes of fixing issues with it, it doesn't make me want to look into the issue.

So, sorry for ranting and the angry post, but luckily there are other people who might be less picky than I am :P

**Comment by haf** [comment] 2016-08-17 12:18
I have every intention of making it work out of the box. It worked on my machine ;) and I haven't gotten your feedback before – now I will go and fix it! I'll let you know.

**Comment by eriwen** [comment] 2016-12-11 05:28
This issue isn't yet actionable and hasn't had a response on a few months, so I'm closing it as dormant. Please reopen it if a small reproducable example is developed.

**Closed by eriwen** 2016-12-11 05:28 UTC

**Comment by haf** [comment] 2016-12-11 08:06
It's completely reproducible and I had to wait 4 months before I even got a reply, though.
