### ISSUE TITLE
Resolving sourcemaps

### ISSUE THREAD

**Issue by XBDRX** [stacktracejs/stacktrace.js#127] opened 2015-09-13 19:37 UTC
Hi

I'm using Gulp+Webpack+React.  I've added stacktrace.js to the mix but the exception files and line numbers are always reported in the bundles rather than the original files.

I've previously used stacktrace (stable build) with Gulp+Webpack+Angular without problem so am I just doing something wrong?

**Comment by eriwen** [comment] 2015-09-13 19:58
I'm going to assume that you're using the version of stacktrace.js that is on the master branch (basically 1.0 beta) which supports sourcemaps. 

We got a question similar to this a few months back. They provided [an example repo](https://github.com/mbrgm/stacktrace-js-sourcemaps-example). 

Depending on the reason sourcemaps aren't resolved, there may be useful information in the Promise errback function. [This change](https://github.com/mbrgm/stacktrace-js-sourcemaps-example/pull/1/files) fixed the other issue. 

If the example repo doesn't help you fix your problem, could you please provide more detail or an example so we can help you further?

**Comment by auchenberg** [comment] 2015-09-17 12:11
Using https://github.com/mbrgm/stacktrace-js-sourcemaps-example/pull/1/files, I'm seeing some wrong request made by stacktrace.ks.js where the ``webpack://`` protocol prefixes are included.

From Chrome DevTools console:
![test-1](https://cloud.githubusercontent.com/assets/173559/9932642/d95620d0-5d45-11e5-940f-0307556b92ec.jpg)

Are these prefixes not supported, or is it a bug within ``stacktrace-gps``?

**Comment by eriwen** [comment] 2015-09-20 22:25
This should be working correctly since https://github.com/stacktracejs/stacktrace-gps/pull/18 has been merged and pushed. 

Would be awesome if someone other than I can confirm that.

**Comment by gbaumgart** [comment] 2015-10-23 12:29
just a question, how do disable loading source maps at all. i am already using source files....

**Comment by eriwen** [comment] 2015-10-25 22:10
@gbaumgart The best way to do that is to enable offline mode. All stacktrace.js methods accept `{offline: true}` which prevents all network requests. In the future, we may give an option to specifically disable source maps.

**Comment by eriwen** [comment] 2015-11-29 23:16
I believe the OP's request was fulfilled here. Please open a new issue if there is anything unaddressed here.

**Closed by eriwen** 2015-11-29 23:16 UTC
